### ISSUE TITLE
How to get the results shown in Table 3?

### ISSUE THREAD

**Issue by au-revoir** [ROIM1998/APT#2]
Hi,
I have followed the command `bash scripts/adaptpruning/llama_2_7b_alpaca_gpt4.sh` with the alpaca_gpt data downloaded from `https://github.com/Instruction-Tuning-with-GPT-4/GPT-4-LLM/blob/main/data/alpaca_gpt4_data.json`. After training the model, how do I get the results for APT given in Table 3? Is there a separate evaluation script?

**Comment by ROIM1998** [comment]
Hi! Thanks for your interest in our work.
We used the evaluation script in `lm-eval-harness` to evaluate our pruned model: https://github.com/EleutherAI/lm-evaluation-harness 
It requires some code change to the eval scripts to make sure that our pruned model can be correctly loaded. We will release our eval scripts soon!

**Comment by au-revoir** [comment]
Thank you for the prompt response. I will give it an attempt and see.

**Comment by ROIM1998** [comment]
As no further conversations are going on, I will close this issue.

Feel free to let me know if you have any more questions!
