### ISSUE TITLE
Training memory measurements

### ISSUE THREAD

**Issue by jsvir** [ROIM1998/APT#3]
Hi,

When you measure the training memory - does it include the base model parameters or only trainable parameters? 
I'm confused since the gradients are computed only for the adaptor, but the base model should reside also on the GPU device and consume GPU memory.

Thanks!

**Comment by ROIM1998** [comment]
Thank you for your interest in our work. In APT training, the base model and adapters are all being put in the GPU memory. As a result, when considering the training memory consumption, the parameters of the base model are also considered. In practice, we use `torch.cuda.max_memory_allocated` to measure the training GPU memory consumption.

If you have any further questions, please let me know!
